# Generated by Django 5.0.6 on 2024-09-27 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="company_that_makes_it",
        ),
        migrations.RemoveField(
            model_name="car",
            name="manufacturer",
        ),
        migrations.DeleteModel(
            name="Fruit",
        ),
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="group",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="person",
        ),
        migrations.RemoveField(
            model_name="person",
            name="place",
        ),
        migrations.RemoveField(
            model_name="person",
            name="poll",
        ),
        migrations.RemoveField(
            model_name="person",
            name="sites",
        ),
        migrations.RemoveField(
            model_name="pizza",
            name="toppings",
        ),
        migrations.DeleteModel(
            name="Car",
        ),
        migrations.DeleteModel(
            name="Manufacturer",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
        migrations.DeleteModel(
            name="Place",
        ),
        migrations.DeleteModel(
            name="Poll",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.DeleteModel(
            name="Site",
        ),
        migrations.DeleteModel(
            name="Pizza",
        ),
        migrations.DeleteModel(
            name="Topping",
        ),
    ]
